---
title: "script"
author: "Li Ying"
date: "11 July 2015"
output: html_document
---

### Executive Summary

### Data
- Participant number: 33
- `Free Will`: 10 questions ***substracted*** from *Free Will and Determinism Scale* ([Rakos et al. 2008](http://agencyandresponsibility.typepad.com/files/competing-free-will-and-responsibility-scales.pdf))
- `Free Association task`: each participants were given 73 **cue words**. For each of cue words, they were instructed to write down 3 words/**responses** that they think is most relevant to the **cue words**. The result will be mentioned as **word data** in the following text.

### Data Process
1. Group participants into two categories: *high free will group* and *low free will group* using mean of Free Will Scale as cut-off line. 
2. Split word association data into two: those generated by High free will group and Low free will group
3. Clean word data. Steps includes:
    * change all capital letter to lower case
    * remove all numbers, stop words
    * stem words, so that various forms derived from a stem would be taken as the same when counting word frequency
4. Build term-document matrix. Each row represent a response and each column represent a cue word, and entry is number of occurrence of the response in cue words.

### Exploratory Data Analysis

#### Histogram of response number
The number of unique response to the 73 cue words were plotted in the histogram below. High number means more spread of the response and low number suggests more clustering of the reponse. The distribution is normal. 

#### Cluster Dendrogram 
Cluster Dendrogram were plotted. Both groups shows that most clue words merges at a high y-axis, suggesting similarity between clue words are quite low. 

#### Minimum Spanning Trees (MST)
Two groups were different by qualitative examination of the MST visualization. The graph of Low Free Will Group looks more modular while the High Free Will Group looks more spread out.
  
#### Association Network Graph
- Association Network were only plotted on those cue words that have correlation > 0.2
- The edge were colored according to correlatonal strenth between nodes, followed sequence of red, blue and grey representing correlation >0.5, >0.4, and else.
- The length of edge is weighted by correlational strength between nodes. 

### Statistical analysis on association network graph
- I examined whether differences between`network parameters`(diameter/D, clustering coefficient/CC, avergae path length/APL) were statistically significant by applying the bootstrap method (Efron, 1979) to simulate partial random high and low networks and compared these networks (Kenett et al., 2013; Kenett, Anaki, et al., 2014).    

- This procedure had a twofold rationale: (1) if the two networks truly differ from each other, then any sub-network consisting of the same nodes in both networks should also be different; and (2) the bootstrap method enables the generation of many simulated partial HIGH and LOW networks, allowing for statistical examination of the difference between the two networks. 

- **Procedure**: In order to conduct the bootstrapping procedure, half of the cue words (nodes) were randomly chosen. Then partial HIGH and LOW networks were constructed separately using these random nodes, based on the entire sample. This method is known as the without replacement bootstrap (Bertail, 1997; Politis & Romano, 1994; Shao, 2003). Finally, for each partial HIGH and LOW network, CC, ASPL, and D  measures were computed. This procedure was simulated with 1000 realizations.

```{r echo=FALSE,message=FALSE}
#xxx
x<-2
x
```


